M48
; DRILL file {KiCad 9.0.7} date 2026-02-01T21:09:57+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-01T21:09:57+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.000
%
G90
G05
T1
X175.92Y-87.0
X186.08Y-87.0
T2
X177.19Y-84.46
X183.54Y-81.92
T3
X181.0Y-87.0
M30
